load captura.mat;
subplot(4, 2, 1);
plot(dados(:,1));
ylabel('Posicao do motor 1');
subplot(4, 2, 2);
plot(dados(:,2));
ylabel('Posicao do motor 2');
subplot(4, 2, 3);
plot(dados(:,3));
ylabel('Posicao do motor 3');
subplot(4, 2, 4);
plot(dados(:,4));
ylabel('Posicao do motor 4');
subplot(4, 2, 5);
plot(dados(:,5));
ylabel('Posicao capturada em X');
subplot(4, 2, 6);
plot(dados(:,6));
ylabel('Posicao capturada em Y');
subplot(4, 2, 7);
plot(dados(:,7));
ylabel('Posicao capturada em Z');